name: Black

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black .  # This will format your code

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Apply black formatting'
        branch: ${{ github.head_ref }}
        file_pattern: '*.py'  # Only commit changes to Python files